-- PraxisPrep Question Seed — First 15 Questions
-- Run after schema.sql in Supabase SQL Editor

INSERT INTO questions (stem, options, explanation, incorrect_explanations, content_category, subcategory, big_nine, difficulty, tags, clinical_setting, reference_sources) VALUES

-- ===== CATEGORY I: Foundations & Professional Practice =====

('According to the ASHA Code of Ethics, which of the following would constitute a violation of Principle I?',
 '[{"id":"a","text":"Referring a patient to another SLP who has more expertise in a specific disorder area","isCorrect":false},{"id":"b","text":"Providing services in an area where the clinician has not received adequate training or education","isCorrect":true},{"id":"c","text":"Declining to provide services to a patient whose insurance does not cover speech therapy","isCorrect":false},{"id":"d","text":"Recommending discharge when a patient has reached maximum benefit from therapy","isCorrect":false}]',
 'Principle I of the ASHA Code of Ethics states that individuals shall honor their responsibility to hold paramount the welfare of persons they serve professionally. Providing services outside one''s scope of competence directly violates this principle, as it puts the patient at risk of receiving inadequate or harmful treatment.',
 '{"a":"Referring to a more qualified clinician actually demonstrates ethical practice and adherence to scope of competence — this supports Principle I.","c":"While access to care is important, declining services based on insurance coverage is a systemic issue, not an ethics violation under Principle I. The SLP should help identify alternative resources.","d":"Recommending discharge when maximum benefit is reached is clinically appropriate and ethical — continuing unnecessary treatment would be the violation."}',
 'I', 'I.B.5', ARRAY['Professional Practice'], 'application', ARRAY['ethics', 'ASHA', 'scope of practice'], NULL, ARRAY['ASHA Code of Ethics (2023)']),

('At what age would you typically expect a child to produce 2-word combinations (e.g., "more milk," "daddy go")?',
 '[{"id":"a","text":"12 months","isCorrect":false},{"id":"b","text":"18-24 months","isCorrect":true},{"id":"c","text":"30-36 months","isCorrect":false},{"id":"d","text":"9-12 months","isCorrect":false}]',
 'Two-word combinations typically emerge between 18-24 months of age. This milestone follows the single-word stage (around 12 months) and precedes telegraphic speech. By 24 months, children typically have a vocabulary of approximately 200-300 words and begin combining words into simple phrases.',
 '{"a":"At 12 months, children are typically producing their first true words (1-3 words). Two-word combinations come later in development.","c":"By 30-36 months, children are already producing 3-4 word sentences and using early grammatical morphemes. Two-word combinations would be expected much earlier.","d":"At 9-12 months, children are in the pre-linguistic stage using babbling and possibly producing their first word around 12 months."}',
 'I', 'I.A.1', ARRAY['Receptive & Expressive Language'], 'recall', ARRAY['development', 'milestones', 'pediatric', 'language'], NULL, ARRAY['CDC Developmental Milestones', 'Paul & Norbury: Language Disorders from Infancy through Adolescence']),

('Which federal legislation mandates that children with disabilities ages 3-21 receive a free appropriate public education (FAPE) in the least restrictive environment?',
 '[{"id":"a","text":"Section 504 of the Rehabilitation Act","isCorrect":false},{"id":"b","text":"Americans with Disabilities Act (ADA)","isCorrect":false},{"id":"c","text":"Individuals with Disabilities Education Act (IDEA)","isCorrect":true},{"id":"d","text":"Health Insurance Portability and Accountability Act (HIPAA)","isCorrect":false}]',
 'IDEA is the federal law that guarantees FAPE for children with disabilities ages 3-21. It mandates evaluation, IEP development, and services in the least restrictive environment (LRE). Part B covers ages 3-21, while Part C covers early intervention for birth to age 3.',
 '{"a":"Section 504 provides civil rights protections against discrimination for individuals with disabilities but does not specifically mandate FAPE with the same procedural protections as IDEA. A 504 plan is less comprehensive than an IEP.","b":"The ADA prohibits discrimination against individuals with disabilities in public life but does not specifically address special education services or FAPE.","d":"HIPAA governs the privacy and security of health information. It has no direct relationship to special education services."}',
 'I', 'I.B.6', ARRAY['Professional Practice'], 'recall', ARRAY['legislation', 'IDEA', 'FAPE', 'schools', 'pediatric'], 'schools', ARRAY['IDEA (2004)', 'ASHA Practice Portal: IDEA']),

('A researcher reports a test-retest reliability coefficient of 0.92 for a new articulation assessment. What does this indicate?',
 '[{"id":"a","text":"The test measures what it claims to measure","isCorrect":false},{"id":"b","text":"Scores are consistent when the test is administered on two separate occasions","isCorrect":true},{"id":"c","text":"The test has strong internal consistency among items","isCorrect":false},{"id":"d","text":"Two different examiners would obtain the same score","isCorrect":false}]',
 'Test-retest reliability measures the stability of scores over time — when the same test is given to the same individuals on two different occasions, a high coefficient (0.92) indicates scores are very consistent. This is distinct from validity (measuring what it claims), internal consistency (Cronbach''s alpha), and inter-rater reliability.',
 '{"a":"This describes validity (criterion, content, or construct), not reliability. Validity and reliability are different psychometric properties.","c":"Internal consistency is measured by Cronbach''s alpha or split-half reliability, not test-retest. Internal consistency evaluates whether items within a test measure the same construct.","d":"This describes inter-rater reliability, which measures agreement between different examiners scoring the same performance."}',
 'I', 'I.B.7', ARRAY['Professional Practice'], 'application', ARRAY['research', 'EBP', 'psychometrics', 'assessment'], NULL, ARRAY['Hegde & Freed: Assessment of Communication Disorders in Adults']),

-- ===== CATEGORY II: Screening, Assessment, Eval & Diagnosis =====

('During an MBSS/VFSS, the SLP observes that barium residue remains in the valleculae after each swallow. This finding is most suggestive of impaired:',
 '[{"id":"a","text":"Tongue base retraction","isCorrect":true},{"id":"b","text":"Laryngeal elevation","isCorrect":false},{"id":"c","text":"Velopharyngeal closure","isCorrect":false},{"id":"d","text":"Upper esophageal sphincter opening","isCorrect":false}]',
 'Vallecular residue after swallowing is primarily indicative of reduced tongue base retraction. The tongue base must contact the posterior pharyngeal wall to generate sufficient pressure to propel the bolus through the pharynx. When tongue base retraction is impaired, the bolus tends to collect in the valleculae (the space between the tongue base and the epiglottis).',
 '{"b":"Impaired laryngeal elevation would more likely result in reduced airway protection and potentially aspiration, though it can contribute to pharyngeal residue. Pyriform sinus residue is more associated with laryngeal/UES issues than vallecular residue.","c":"Velopharyngeal closure is relevant to preventing nasal regurgitation during the pharyngeal swallow, not to vallecular clearance.","d":"Impaired UES opening typically results in pyriform sinus residue (the piriform sinuses are adjacent to the UES), not specifically vallecular residue."}',
 'II', 'II.C.9', ARRAY['Feeding & Swallowing'], 'analysis', ARRAY['dysphagia', 'MBSS', 'VFSS', 'instrumental', 'adult'], 'acute care', ARRAY['Logemann: Evaluation and Treatment of Swallowing Disorders', 'ASHA Practice Portal: Adult Dysphagia']),

('A bilingual Spanish-English speaking child scores below age expectations on a standardized English language assessment. The MOST appropriate next step is to:',
 '[{"id":"a","text":"Diagnose the child with a language disorder and begin treatment in English","isCorrect":false},{"id":"b","text":"Assess the child''s language abilities in Spanish and compare to bilingual development norms","isCorrect":true},{"id":"c","text":"Wait 6 months and retest to see if English skills improve with more exposure","isCorrect":false},{"id":"d","text":"Refer the child for a cognitive assessment to rule out intellectual disability","isCorrect":false}]',
 'Assessment must consider both languages to differentiate a language difference from a language disorder. A bilingual child may demonstrate distributed competence — stronger skills in one language for certain domains. Testing only in English can result in over-identification. The SLP should assess in both languages, use dynamic assessment, gather language history, and compare to bilingual development norms.',
 '{"a":"Diagnosing based solely on English assessment ignores the child''s linguistic background and may result in misdiagnosis. A language difference (typical bilingual development) is not a disorder.","c":"A ''wait and see'' approach delays appropriate assessment and is not recommended. Comprehensive bilingual assessment should be completed promptly.","d":"Jumping to cognitive testing is premature without first completing a comprehensive bilingual language assessment. Low English scores alone do not suggest intellectual disability."}',
 'II', 'II.B', ARRAY['Receptive & Expressive Language'], 'clinical_reasoning', ARRAY['bilingual', 'assessment', 'cultural', 'pediatric', 'language difference'], 'schools', ARRAY['ASHA Practice Portal: Bilingual Service Delivery', 'Goldstein & Fabiano-Smith: Bilingual Speech Sound Development']),

('An audiogram shows normal hearing sensitivity bilaterally from 250-2000 Hz with a precipitous drop to severe sensorineural hearing loss from 3000-8000 Hz. This pattern is MOST consistent with:',
 '[{"id":"a","text":"Otitis media with effusion","isCorrect":false},{"id":"b","text":"Noise-induced hearing loss","isCorrect":true},{"id":"c","text":"Otosclerosis","isCorrect":false},{"id":"d","text":"Meniere''s disease","isCorrect":false}]',
 'Noise-induced hearing loss (NIHL) classically presents as a high-frequency sensorineural hearing loss, often with a characteristic ''noise notch'' around 3000-6000 Hz. The pattern of normal low-frequency hearing with a sharp high-frequency drop is a hallmark of NIHL.',
 '{"a":"Otitis media with effusion typically produces a flat or low-frequency conductive hearing loss (air-bone gap), not a high-frequency sensorineural pattern.","c":"Otosclerosis causes a conductive hearing loss (particularly at low frequencies) due to fixation of the stapes footplate. It would show an air-bone gap on audiometry.","d":"Meniere''s disease typically presents with a low-frequency sensorineural hearing loss (particularly in early stages), which is the opposite of the pattern described."}',
 'II', 'II.C.8', ARRAY['Hearing'], 'analysis', ARRAY['audiology', 'audiogram', 'hearing loss', 'adult'], NULL, ARRAY['Bess & Humes: Audiology: The Fundamentals']),

('Which assessment finding would be MOST indicative of childhood apraxia of speech (CAS) rather than a phonological disorder?',
 '[{"id":"a","text":"Consistent substitution patterns across word positions","isCorrect":false},{"id":"b","text":"Inconsistent production errors on repeated trials of the same word","isCorrect":true},{"id":"c","text":"Deletion of final consonants in multisyllabic words","isCorrect":false},{"id":"d","text":"Difficulty with phonological awareness tasks","isCorrect":false}]',
 'Inconsistent production errors on repeated trials of the same word is one of the three consensus-based features of CAS identified by ASHA (2007). The other two features are disrupted coarticulatory transitions (between sounds and syllables) and inappropriate prosody. Phonological disorders show consistent, predictable error patterns, while CAS shows variable and inconsistent errors.',
 '{"a":"Consistent substitution patterns are characteristic of phonological disorders, where error patterns are predictable and systematic (e.g., fronting, stopping). CAS shows the opposite — inconsistency.","c":"Final consonant deletion is a phonological process, not specific to CAS. It occurs in typical development and in phonological disorders.","d":"Difficulty with phonological awareness can occur in many disorders and is not a distinguishing feature of CAS."}',
 'II', 'II.C.1', ARRAY['Speech Sound Production'], 'analysis', ARRAY['CAS', 'apraxia', 'motor speech', 'pediatric', 'differential diagnosis'], NULL, ARRAY['ASHA Technical Report on CAS (2007)', 'Strand & McCauley: Differential Diagnosis of Severe Speech Disorders']),

-- ===== CATEGORY III: Treatment Planning & Implementation =====

('The Lee Silverman Voice Treatment (LSVT LOUD) program is MOST appropriate for patients with:',
 '[{"id":"a","text":"Spasmodic dysphonia","isCorrect":false},{"id":"b","text":"Hypophonia secondary to Parkinson''s disease","isCorrect":true},{"id":"c","text":"Vocal fold nodules","isCorrect":false},{"id":"d","text":"Unilateral vocal fold paralysis","isCorrect":false}]',
 'LSVT LOUD was specifically developed for and has the strongest evidence base for treating hypophonia in individuals with Parkinson''s disease. It targets vocal loudness through intensive treatment (4 days/week for 4 weeks) with the single focus of "Think LOUD!" The program addresses the sensory processing deficit in PD where patients perceive their loud voice as ''too loud.''',
 '{"a":"Spasmodic dysphonia is a neurological voice disorder typically treated with botulinum toxin injections. LSVT LOUD targets loudness, not the adductor/abductor spasms of SD.","c":"Vocal fold nodules are treated with voice therapy focusing on vocal hygiene, reducing phonotraumatic behaviors, and resonant voice therapy — not intensive loudness training.","d":"Unilateral vocal fold paralysis may be treated with injection medialization, thyroplasty, or voice therapy targeting vocal fold adduction (e.g., pushing exercises). LSVT LOUD is not the primary approach."}',
 'III', 'III.C.3', ARRAY['Voice, Resonance & Motor Speech'], 'application', ARRAY['LSVT', 'Parkinsons', 'voice', 'named treatment', 'adult'], 'outpatient', ARRAY['Ramig et al. (2001)', 'ASHA Practice Portal: Voice Disorders']),

('When using the Lidcombe Program for a preschool-age child who stutters, the parent is trained to provide:',
 '[{"id":"a","text":"Structured drills of fluency-enhancing techniques","isCorrect":false},{"id":"b","text":"Verbal contingencies for both stutter-free speech and unambiguous stuttering","isCorrect":true},{"id":"c","text":"Delayed auditory feedback during daily practice sessions","isCorrect":false},{"id":"d","text":"Cognitive-behavioral strategies to reduce speech anxiety","isCorrect":false}]',
 'The Lidcombe Program is a parent-delivered behavioral treatment for early childhood stuttering. Parents are trained to provide verbal contingencies: praise and acknowledgment for stutter-free speech, and occasional self-correction requests for unambiguous stuttering moments. Treatment occurs in natural conversations, not structured drills.',
 '{"a":"The Lidcombe Program does not involve teaching fluency-shaping techniques or structured drills. It is a behavioral operant approach delivered in natural speaking contexts.","c":"Delayed auditory feedback (DAF) is used in fluency-shaping programs for older children and adults, not in the Lidcombe Program for preschoolers.","d":"Cognitive-behavioral strategies are used with older children, adolescents, and adults who stutter. Preschool children are not developmentally ready for CBT approaches."}',
 'III', 'III.C.2', ARRAY['Fluency'], 'application', ARRAY['stuttering', 'Lidcombe', 'pediatric', 'named treatment', 'fluency'], NULL, ARRAY['Onslow et al.: Lidcombe Program Treatment Guide', 'ASHA Practice Portal: Childhood Fluency Disorders']),

('For a patient with severe Broca''s aphasia, which treatment approach focuses on training the production of script-like functional phrases for daily communication?',
 '[{"id":"a","text":"Melodic Intonation Therapy (MIT)","isCorrect":false},{"id":"b","text":"Verb Network Strengthening Treatment (VNeST)","isCorrect":false},{"id":"c","text":"Script Training","isCorrect":true},{"id":"d","text":"Semantic Feature Analysis (SFA)","isCorrect":false}]',
 'Script Training involves developing and practicing functional scripts (routine phrases and conversations) relevant to the patient''s daily life. It leverages the preserved ability to produce overlearned, automatic speech. Through intensive practice, scripted utterances become automatic and can be used in functional communication contexts.',
 '{"a":"MIT uses melodic patterns and rhythm to facilitate propositional speech, leveraging right hemisphere contributions. While useful for Broca''s aphasia, it focuses on intonation patterns rather than functional script practice.","b":"VNeST targets verb retrieval and associated thematic roles to strengthen verb networks. It is a word-retrieval treatment, not a functional script-based approach.","d":"SFA targets word retrieval by activating semantic features of target words. It is an impairment-based approach for anomia, not focused on practicing functional conversation scripts."}',
 'III', 'III.C.4', ARRAY['Receptive & Expressive Language'], 'application', ARRAY['aphasia', 'Brocas', 'adult', 'named treatment', 'neurogenic'], 'outpatient', ARRAY['Cherney et al. (2008): Script Training', 'ASHA Practice Portal: Aphasia']),

('A 5-year-old child with autism spectrum disorder has limited functional communication. The child uses some single words but relies primarily on grabbing, pointing, and leading adults by the hand. Which would be the MOST appropriate initial AAC intervention?',
 '[{"id":"a","text":"Wait until the child develops more verbal skills before introducing AAC","isCorrect":false},{"id":"b","text":"Introduce a high-tech speech-generating device with 100+ symbols","isCorrect":false},{"id":"c","text":"Begin with the Picture Exchange Communication System (PECS) starting at Phase I","isCorrect":true},{"id":"d","text":"Teach American Sign Language as a total communication approach","isCorrect":false}]',
 'PECS is an evidence-based AAC system specifically designed for children with ASD who have limited functional communication. Phase I teaches the physical exchange of a picture for a desired item — building the foundational communicative act of initiation. PECS systematically builds from simple exchanges to sentence construction and commenting. It does not require imitation skills (unlike sign language) and builds on the child''s existing communication behaviors.',
 '{"a":"Research consistently shows that AAC does NOT inhibit verbal language development — it supports it. Waiting is not recommended and denies the child access to functional communication.","b":"Starting with a high-tech device with 100+ symbols is overwhelming and not developmentally appropriate for a child at this communication level. AAC should start with the child''s current abilities.","d":"Sign language requires motor imitation skills that many children with ASD find challenging. It also requires communication partners to know signs. PECS is generally more accessible for this population."}',
 'III', 'III.C.7', ARRAY['AAC', 'Social Communication / Pragmatics'], 'clinical_reasoning', ARRAY['AAC', 'PECS', 'autism', 'pediatric', 'named treatment'], 'schools', ARRAY['Bondy & Frost: PECS Training Manual', 'ASHA Practice Portal: AAC']),

('When developing treatment goals for a patient, which of the following represents a SMART goal?',
 '[{"id":"a","text":"The patient will improve swallowing function","isCorrect":false},{"id":"b","text":"The patient will produce /s/ in all positions of words with 80% accuracy across 3 consecutive sessions","isCorrect":true},{"id":"c","text":"The patient will communicate better with family members","isCorrect":false},{"id":"d","text":"The patient will make progress on language goals","isCorrect":false}]',
 'SMART goals are Specific, Measurable, Achievable, Relevant, and Time-bound. Option B specifies the exact target (/s/), context (all positions), criterion (80% accuracy), and condition (3 consecutive sessions). The other options are vague and unmeasurable — they lack specific criteria, timelines, and measurable benchmarks.',
 '{"a":"\"Improve swallowing function\" is vague — it does not specify what aspect of swallowing, to what degree, or by when. It is not measurable.","c":"\"Communicate better\" is subjective and unmeasurable. A SMART goal would specify what communication behavior, in what context, and with what criterion.","d":"\"Make progress\" is not measurable. Without specifying which goals, what progress looks like, and by when, this cannot be objectively evaluated."}',
 'III', 'III.A', ARRAY['Professional Practice'], 'application', ARRAY['treatment planning', 'goals', 'documentation'], NULL, ARRAY['Roth & Worthington: Treatment Resource Manual for SLP']),

('The Mendelsohn maneuver is a swallowing exercise that primarily targets:',
 '[{"id":"a","text":"Tongue base retraction","isCorrect":false},{"id":"b","text":"Duration and extent of laryngeal elevation and UES opening","isCorrect":true},{"id":"c","text":"Supraglottic airway closure","isCorrect":false},{"id":"d","text":"Oral bolus formation and propulsion","isCorrect":false}]',
 'The Mendelsohn maneuver involves voluntarily prolonging and increasing the extent of laryngeal elevation during the swallow. This increases the duration that the upper esophageal sphincter (UES) remains open, facilitating bolus transfer from the pharynx to the esophagus. It is a rehabilitative exercise that targets the pharyngeal-esophageal mechanism.',
 '{"a":"Tongue base retraction is targeted by exercises like the Masako (tongue-hold) maneuver and effortful swallow, not the Mendelsohn.","c":"Supraglottic airway closure is targeted by the supraglottic and super-supraglottic swallow maneuvers, which involve voluntary breath-hold before and during the swallow.","d":"Oral bolus formation and propulsion are addressed through oral motor exercises and lingual strengthening, not the Mendelsohn maneuver which targets the pharyngeal/UES mechanism."}',
 'III', 'III.C.9', ARRAY['Feeding & Swallowing'], 'recall', ARRAY['dysphagia', 'Mendelsohn', 'swallowing exercise', 'named treatment', 'adult'], 'acute care', ARRAY['Logemann: Evaluation and Treatment of Swallowing Disorders']);

-- Add flashcards
INSERT INTO flashcards (front, back, category, subcategory, tags) VALUES
('CN V (Trigeminal)', 'Motor: muscles of mastication (temporalis, masseter, pterygoids), tensor veli palatini, tensor tympani, mylohyoid, anterior belly of digastric. Sensory: face sensation (3 divisions: ophthalmic V1, maxillary V2, mandibular V3). Damage: jaw deviation toward weak side, reduced facial sensation.', 'Anatomy', 'Cranial Nerves', ARRAY['cranial nerves', 'anatomy']),
('CN VII (Facial)', 'Motor: muscles of facial expression, stapedius, stylohyoid, posterior belly of digastric. Sensory: taste (anterior 2/3 of tongue). Parasympathetic: submandibular, sublingual, lacrimal glands. Damage: Bell''s palsy — facial droop, hyperacusis, reduced taste.', 'Anatomy', 'Cranial Nerves', ARRAY['cranial nerves', 'anatomy']),
('CN IX (Glossopharyngeal)', 'Motor: stylopharyngeus. Sensory: taste (posterior 1/3 of tongue), pharyngeal sensation, gag reflex (afferent). Parasympathetic: parotid gland. Key for swallowing: triggers pharyngeal swallow via sensory input.', 'Anatomy', 'Cranial Nerves', ARRAY['cranial nerves', 'anatomy', 'dysphagia']),
('CN X (Vagus)', 'Motor: pharyngeal constrictors, levator veli palatini, intrinsic laryngeal muscles (via recurrent laryngeal nerve). Sensory: laryngeal sensation. Key branches: pharyngeal, superior laryngeal (SLN), recurrent laryngeal (RLN). Damage: unilateral VF paralysis, breathy voice, swallowing difficulty.', 'Anatomy', 'Cranial Nerves', ARRAY['cranial nerves', 'anatomy', 'voice', 'dysphagia']),
('CN XII (Hypoglossal)', 'Motor: intrinsic and extrinsic tongue muscles. Damage: tongue deviates toward weak side on protrusion. Essential for oral phase of swallowing and speech articulation.', 'Anatomy', 'Cranial Nerves', ARRAY['cranial nerves', 'anatomy']),
('IDDSI Level 0 — Thin Liquids', 'Flows like water. No modification needed. Can drink through any type of teat/nipple, cup, or straw. Example: water, tea, coffee, juice. Testing: flows through a syringe in ≤1 second.', 'Dysphagia', 'IDDSI Framework', ARRAY['IDDSI', 'dysphagia', 'diet']),
('IDDSI Level 4 — Pureed', 'Smooth, no lumps, not sticky. Does not require chewing. Falls off spoon in a single spoonful when tilted. Cannot be sucked through a straw. Can be piped or molded. Example: smooth pudding, pureed fruit.', 'Dysphagia', 'IDDSI Framework', ARRAY['IDDSI', 'dysphagia', 'diet']),
('IDDSI Level 7 — Regular/Easy to Chew', 'Level 7 = normal, everyday foods of various textures. No restrictions. Easy to Chew = soft and tender but not mashed. Can be eaten with fork, spoon, or chopsticks.', 'Dysphagia', 'IDDSI Framework', ARRAY['IDDSI', 'dysphagia', 'diet']),
('Penetration-Aspiration Scale (PAS)', '1 = no entry into airway. 2 = enters airway, above VFs, ejected. 3 = above VFs, not ejected. 4 = contacts VFs, ejected. 5 = contacts VFs, not ejected. 6 = passes below VFs, ejected. 7 = passes below VFs, not ejected, patient response. 8 = passes below VFs, no effort to eject (SILENT ASPIRATION).', 'Assessment', 'Swallowing Scales', ARRAY['PAS', 'aspiration', 'dysphagia', 'assessment']),
('Silent Aspiration', 'Material passes below the true vocal folds with NO cough response (PAS score of 8). Cannot be detected by clinical/bedside evaluation alone — requires instrumental assessment (MBSS or FEES). Common in: stroke, Parkinson''s, TBI, reduced laryngeal sensation.', 'Dysphagia', 'Key Concepts', ARRAY['aspiration', 'dysphagia', 'instrumental']),
('Phonological Processes — Expected Ages of Suppression', 'Fronting: by 3;6. Stopping: by 3;0-5;0 (varies by sound). Final consonant deletion: by 3;3. Cluster reduction: by 4;0-5;0. Gliding: by 5;0-6;0. Deaffrication: by 4;0. If present beyond these ages, may indicate phonological disorder.', 'Development', 'Speech Sound Development', ARRAY['phonological processes', 'development', 'pediatric']),
('Brown''s Stages of Morphological Development', 'Stage I (MLU 1.0-2.0): 2-word combinations. Stage II (MLU 2.0-2.5): present progressive -ing, in, on. Stage III (MLU 2.5-3.0): irregular past, possessive -s, uncontractible copula. Stage IV (MLU 3.0-3.5): articles, regular past -ed, third person regular -s. Stage V (MLU 3.5-4.0): third person irregular, uncontractible auxiliary, contractible copula, contractible auxiliary.', 'Development', 'Language Development', ARRAY['morphology', 'development', 'Brown', 'pediatric']),
('Trisomy 21 (Down Syndrome) — SLP Considerations', 'Common: low muscle tone (hypotonia), macroglossia, hearing loss (recurrent OM), delayed speech/language, intelligibility challenges. Language: receptive > expressive typically. Phonology: cluster reduction, final consonant deletion persist. Fluency: higher incidence of stuttering. Feeding: may need modified textures due to oral motor challenges.', 'Syndromes', 'Genetic Conditions', ARRAY['Down syndrome', 'Trisomy 21', 'genetic', 'pediatric']),
('22q11.2 Deletion Syndrome (Velocardiofacial/DiGeorge)', 'Features: VPI/cleft palate, cardiac defects, characteristic facial features, learning disabilities, immune deficiency. SLP focus: velopharyngeal insufficiency (VPI), hypernasal resonance, compensatory articulation patterns (glottal stops, pharyngeal fricatives). May need pharyngeal flap or sphincter pharyngoplasty.', 'Syndromes', 'Genetic Conditions', ARRAY['22q11.2', 'VPI', 'resonance', 'genetic', 'pediatric']),
('Shaker Exercise (Head-Lifting)', 'Rehabilitative exercise targeting UES opening via suprahyoid muscle strengthening. Position: supine (lying on back). Action: lift head to see toes without lifting shoulders. Protocol: isometric (3 x 1-minute holds) + isokinetic (30 repetitions). Contraindications: cervical spine issues, neck pain. Evidence: improves UES opening, reduces pyriform sinus residue.', 'Treatment', 'Dysphagia Exercises', ARRAY['Shaker', 'dysphagia', 'exercise', 'UES']);
